name: Build Docs
on:
  pull_request:
    branches: dev
  workflow_call:
    inputs:
      event_name:
        description: "The name of the event that triggered workflow calling this workflow. In other words, the parent workflow"
        required: true
        type: string
    outputs:
      artifact:
        description: "The uploaded docs artifact."
        value: ${{ jobs.build_docs.outputs.artifact }}
      algolia_artifact:
        description: "The uploaded Algolia artifact."
        value: ${{ jobs.build_docs.outputs.algolia_artifact }}
      docs_changed:
        description: "True if documentation files have changed. False if not"
        value: ${{ jobs.build_docs.outputs.docs_changed }}

env:
  INSTANCE: Writerside/d
  DOCKER_VERSION: 243.22562

jobs:
  build_docs:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.define-ids.outputs.artifact }}
      algolia_artifact: ${{ steps.define-ids.outputs.algolia_artifact }}
      docs_changed: ${{ steps.detect_changes.outputs.docs_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes to docs
        id: detect_changes
        run: |
          if [ "${{ inputs.event_name }}" == "workflow_dispatch" ]; then
            echo "docs_changed=true" >> $GITHUB_OUTPUT
            echo "Manual Trigger. Treating as changed"
          elif [ "${{ inputs.event_name }}" == "push" ]; then
            # For pushes, check if any Writerside/ files were changed
            if git diff --name-only HEAD~1 HEAD | grep -q "^Writerside/"; then
              echo "docs_changed=true" >> $GITHUB_OUTPUT
              echo "Documentation changes detected in push"
            else
              echo  "docs_changed=false" >> $GITHUB_OUPUT
              echo "No documentation changes detected in push"
            fi
          else
            # For PRs, check if files in Writerside/ are different from base
            if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "^Writerside/"; then
              echo "docs_changed=true" >> $GITHUB_OUTPUT
              echo "Documentation changes detected in PR"
            else
              echo "docs_changed=false" >> $GITHUB_OUTPUT
              echo "No documentation changes in PR"
            fi
          fi

      - name: Define instance id and artifacts
        id: define-ids
        run: |
          INSTANCE=${INSTANCE#*/}
          INSTANCE_ID_UPPER=$(echo "$INSTANCE" | tr '[:lower:]' '[:upper:]')
          ARTIFACT="webHelp${INSTANCE_ID_UPPER}2-all.zip"
          ALGOLIA_ARTIFACT="algolia-indexes-${INSTANCE_ID_UPPER}.zip"

          # Print the values
          echo "INSTANCE_ID_UPPER: $INSTANCE_ID_UPPER"
          echo "ARTIFACT: $ARTIFACT"
          echo "ALGOLIA_ARTIFACT: $ALGOLIA_ARTIFACT"

          # Set the environment variables and outputs
          echo "INSTANCE_ID_UPPER=$INSTANCE_ID_UPPER" >> $GITHUB_ENV
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV
          echo "ALGOLIA_ARTIFACT=$ALGOLIA_ARTIFACT" >> $GITHUB_ENV
          echo "artifact=$ARTIFACT" >> $GITHUB_OUTPUT
          echo "algolia_artifact=$ALGOLIA_ARTIFACT" >> $GITHUB_OUTPUT

      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          docker-version: ${{ env.DOCKER_VERSION }}
          artifact: ${{ steps.define-ids.outputs.artifact }}

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: artifacts/*
          retention-days: 7
