name: Deploy Docs
on:
  pull_request:
    branches: [master, dev]
    paths: Writerside/**
  push:
    branches: [master, dev]
    paths: Writerside/**
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  prerequisite_build:
    uses: ./.github/workflows/build_docs.yml
    
  deploy_docs:
    if: github.ref == 'refs/heads/master' # Only deploy to Pages from master branch
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: prerequisite_build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Unzip artifact
        run: unzip -O UTF-8 -qq "artifacts/${{ needs.prerequisite_build.outputs.artifact }}" -d dir

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Package and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
